version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: mysql_db
    environment:
      - MYSQL_DATABASE=study
      - MYSQL_ROOT_PASSWORD=924498
      - TZ= Asia/Seoul
    ports:
      - '3307:3306'
    # volumes:
    #   - ./db/data:/var/lib/mysql

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        JAR_FILE: ./build/libs/*.jar
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/study?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=924498
    depends_on:
      - database