version: '3.8'

services:
  database:
    image: mysql
    container_name: gdsc
    environment:
      - MYSQL_DATABASE=springboot
      - MYSQL_ROOT_PASSWORD=924498
      - TZ= Asia/Seoul
    ports:
      - '3307:3306'


  backend:
    image: gdsc
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:mysql://gdsc:3306/springboot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=924498
    depends_on:
      - database
